

export const coursesData = [
  {
    "id": 1,
    "title": "Introduction to Python Programming",
    "categories": ["Programming", "Python", "Beginner"],
    "instructor": "Dr. Emily Chen",
    "duration": "8 weeks",
    "level": "Beginner",
    "students": 15420,
    "rating": 4.8,
    "price": 89.99,
    "language": "English",
    "published": true,
    "image": "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800&q=80"
  },
  {
    "id": 2,
    "title": "Advanced JavaScript: Modern Features and Best Practices",
    "categories": ["Web Development", "JavaScript", "Advanced"],
    "instructor": "Michael Roberts",
    "duration": "10 weeks",
    "level": "Advanced",
    "students": 8920,
    "rating": 4.9,
    "price": 129.99,
    "language": "English",
    "published": true,
    "image": "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=800&q=80"
  },
  {
    "id": 3,
    "title": "Machine Learning with TensorFlow",
    "categories": ["Data Science", "Machine Learning", "AI", "TensorFlow"],
    "instructor": "Dr. Sarah Kumar",
    "duration": "12 weeks",
    "level": "Intermediate",
    "students": 12350,
    "rating": 4.7,
    "price": 149.99,
    "language": "English",
    "published": true,
    "image": "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80"
  },
  {
    "id": 4,
    "title": "UI/UX Design Fundamentals",
    "categories": ["Design", "UI/UX", "Figma"],
    "instructor": "Laura Martinez",
    "duration": "6 weeks",
    "level": "Beginner",
    "students": 21000,
    "rating": 4.9,
    "price": 79.99,
    "language": "English",
    "published": true,
    "image": "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80"
  },
  {
    "id": 5,
    "title": "React and Redux: Building Modern Web Apps",
    "categories": ["Web Development", "React", "JavaScript", "Frontend"],
    "instructor": "James Wilson",
    "duration": "9 weeks",
    "level": "Intermediate",
    "students": 18200,
    "rating": 4.8,
    "price": 119.99,
    "language": "English",
    "published": true,
    "image": "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&q=80"
  },
  {
    "id": 6,
    "title": "Data Structures and Algorithms in Java",
    "categories": ["Computer Science", "Java", "Algorithms", "Interview Prep"],
    "instructor": "Prof. Alan Thompson",
    "duration": "14 weeks",
    "level": "Intermediate",
    "students": 9800,
    "rating": 4.6,
    "price": 139.99,
    "language": "English",
    "published": true,
    "image": "https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=800&q=80"
  },
  {
    "id": 7,
    "title": "Digital Marketing Mastery 2025",
    "categories": ["Marketing", "Digital Marketing", "SEO", "Social Media"],
    "instructor": "Sophie Anderson",
    "duration": "7 weeks",
    "level": "All Levels",
    "students": 27500,
    "rating": 4.9,
    "price": 99.99,
    "language": "English",
    "published": true,
    "image": "https://images.unsplash.com/photo-1557838923-2985c318be48?w=800&q=80"
  },
  {
    "id": 8,
    "title": "Cybersecurity Essentials",
    "categories": ["Cybersecurity", "IT & Security", "Networking"],
    "instructor": "Mark Donovan",
    "duration": "10 weeks",
    "level": "Beginner",
    "students": 16800,
    "rating": 4.8,
    "price": 109.99,
    "language": "English",
    "published": true,
    "image": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80"
  },
  {
    "id": 9,
    "title": "Cloud Computing with AWS",
    "categories": ["Cloud Computing", "AWS", "DevOps"],
    "instructor": "Rachel Patel",
    "duration": "11 weeks",
    "level": "Intermediate",
    "students": 14100,
    "rating": 4.7,
    "price": 159.99,
    "language": "English",
    "published": true,
    "image": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80"
  },
  {
    "id": 10,
    "title": "Full-Stack Web Development Bootcamp",
    "categories": ["Web Development", "Full-Stack", "JavaScript", "Node.js", "React"],
    "instructor": "David Lee",
    "duration": "16 weeks",
    "level": "Beginner to Advanced",
    "students": 32000,
    "rating": 4.9,
    "price": 199.99,
    "language": "English",
    "published": true,
    "image": "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&q=80"
  },
  {
    "id": 11,
    "title": "SQL and Database Management",
    "categories": ["Data Science", "Databases", "SQL"],
    "instructor": "Jennifer Brooks",
    "duration": "6 weeks",
    "level": "Beginner",
    "students": 19500,
    "rating": 4.8,
    "price": 69.99,
    "language": "English",
    "published": true,
    "image": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80"
  },
  {
    "id": 12,
    "title": "DevOps Engineering with Docker & Kubernetes",
    "categories": ["DevOps", "Docker", "Kubernetes", "CI/CD"],
    "instructor": "Thomas Reed",
    "duration": "12 weeks",
    "level": "Advanced",
    "students": 8700,
    "rating": 4.9,
    "price": 179.99,
    "language": "English",
    "published": true,
    "image": "https://images.unsplash.com/photo-1593720219276-0b1eacd0aef3?w=800&q=80"
  },
  {
    "id": 13,
    "title": "Graphic Design with Adobe Photoshop & Illustrator",
    "categories": ["Design", "Graphic Design", "Adobe", "Creative"],
    "instructor": "Emma Clarke",
    "duration": "8 weeks",
    "level": "Intermediate",
    "students": 15200,
    "rating": 4.7,
    "price": 94.99,
    "language": "English",
    "published": true,
    "image": "https://images.unsplash.com/photo-1626785774625-5d5920d68d23?w=800&q=80"
  },
  {
    "id": 14,
    "title": "Artificial Intelligence Fundamentals",
    "categories": ["AI & ML", "Artificial Intelligence", "Machine Learning"],
    "instructor": "Dr. Robert Kim",
    "duration": "10 weeks",
    "level": "Beginner",
    "students": 18900,
    "rating": 4.8,
    "price": 129.99,
    "language": "English",
    "published": true,
    "image": "https://images.unsplash.com/photo-1676299081327-6973e75d25db?w=800&q=80"
  },
  {
    "id": 15,
    "title": "Mobile App Development with Flutter",
    "categories": ["Mobile Development", "Flutter", "Dart", "Cross-Platform"],
    "instructor": "Alex Rivera",
    "duration": "9 weeks",
    "level": "Intermediate",
    "students": 13400,
    "rating": 4.9,
    "price": 109.99,
    "language": "English",
    "published": true,
    "image": "https://images.unsplash.com/photo-1607252650355-f7fd546c3d37?w=800&q=80"
  },
  {
    "id": 16,
    "title": "Blockchain and Cryptocurrency Explained",
    "categories": ["Blockchain", "Cryptocurrency", "Web3"],
    "instructor": "Daniel Wong",
    "duration": "5 weeks",
    "level": "Beginner",
    "students": 22300,
    "rating": 4.6,
    "price": 89.99,
    "language": "English",
    "published": true,
    "image": "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80"
  },
  {
    "id": 17,
    "title": "Project Management Professional (PMP) Prep",
    "categories": ["Business", "Project Management", "PMP", "Certification"],
    "instructor": "Karen Mitchell",
    "duration": "8 weeks",
    "level": "Advanced",
    "students": 11200,
    "rating": 4.8,
    "price": 149.99,
    "language": "English",
    "published": true,
    "image": "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80"
  },
  {
    "id": 18,
    "title": "Ethical Hacking and Penetration Testing",
    "categories": ["Cybersecurity", "Ethical Hacking", "Penetration Testing"],
    "instructor": "Victor Santos",
    "duration": "13 weeks",
    "level": "Advanced",
    "students": 9500,
    "rating": 4.9,
    "price": 189.99,
    "language": "English",
    "published": true,
    "image": "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=800&q=80"
  },
  {
    "id": 19,
    "title": "Data Visualization with Tableau",
    "categories": ["Data Science", "Data Visualization", "Tableau", "Business Intelligence"],
    "instructor": "Olivia Green",
    "duration": "6 weeks",
    "level": "Intermediate",
    "students": 17800,
    "rating": 4.8,
    "price": 89.99,
    "language": "English",
    "published": true,
    "image": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80"
  },
  {
    "id": 20,
    "title": "Game Development with Unity",
    "categories": ["Game Development", "Unity", "C#", "3D"],
    "instructor": "Nathan Cole",
    "duration": "10 weeks",
    "level": "Intermediate",
    "students": 16700,
    "rating": 4.7,
    "price": 124.99,
    "language": "English",
    "published": true,
    "image": "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80"
  }
]