const data = [
    {
        id: 1,
        title: 'The Complete React & Redux Mastery Course (2025)',
        categories: ['Web Development', 'React', 'JavaScript', 'Frontend'],
        instructor: {
            name: 'Alice Johnson',
            title: 'Senior Full-Stack Developer',
            rating: 4.8,
            reviews: 12450,
        },
        description:
            'Go from 0 to expert-level React developer. Build 10 real-world projects, master Hooks, Redux Toolkit, and deploy professional applications.',
        price: 199.99,
        level: 'Intermediate',
        discountPrice: 49.99,
        rating: 4.7,
        totalReviews: 45200,
        studentsEnrolled: 155000,
        lastUpdated: 'October 2025',
        language: 'English',
        durationHours: 45.5,
        isBestseller: true,
        published: true,
        image: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&q=80',
        promotionalVideoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=0',
        totalLessons: 23,
        whatYouWillLearn: [
            'Build complex, scalable user interfaces with React.',
            'Manage application state efficiently using Redux Toolkit and Context API.',
            'Master the latest React features, including Hooks (useState, useEffect, etc.).',
        ],
        curriculum: [
            {
                id: 101,
                title: 'Section 1: React Fundamentals',
                duration: '5 lectures | 3h 15m',
                lessons: ['Introduction to JSX', 'Functional Components', 'State and Props'],
                isPreviewable: true,
            },
            {
                id: 102,
                title: 'Section 2: Advanced React Concepts',
                duration: '6 lectures | 4h 30m',
                lessons: ['Hooks in Depth', 'Custom Hooks', 'Context API', 'Error Boundaries'],
                isPreviewable: false,
            },
            {
                id: 103,
                title: 'Section 3: Introduction to Redux',
                duration: '4 lectures | 3h 0m',
                lessons: ['What is Redux?', 'Actions and Reducers', 'Store Setup', 'Connecting React to Redux'],
                isPreviewable: true,
            },
            {
                id: 104,
                title: 'Section 4: Redux Toolkit',
                duration: '5 lectures | 4h 15m',
                lessons: ['RTK Setup', 'createSlice', 'Async Thunks', 'RTK Query'],
                isPreviewable: false,
            },
            {
                id: 105,
                title: 'Section 5: Building Real-World Projects',
                duration: '8 lectures | 8h 0m',
                lessons: ['Project Planning', 'E-Commerce App', 'Social Media Dashboard', 'Deployment'],
                isPreviewable: true,
            },
        ],
        requirements: ['Basic understanding of HTML, CSS, and JavaScript.'],
    },
    {
        id: 2,
        title: 'Next.js 15: The Ultimate Fullstack Framework',
        categories: ['Full Stack Development', 'Next.js', 'React', 'Server-Side Rendering'],
        instructor: {
            name: 'Ben Miller',
            title: 'Tech Lead at Innovate Solutions',
            rating: 4.6,
            reviews: 9800,
        },
        description:
            'Learn to build modern, production-ready full-stack applications with Next.js App Router, Server Components, and API Routes.',
        price: 149.99,
        level: 'Advanced',
        discountPrice: 39.99,
        rating: 4.6,
        totalReviews: 22100,
        studentsEnrolled: 95000,
        lastUpdated: 'November 2025',
        language: 'English',
        durationHours: 30.0,
        isBestseller: false,
        published: true,
        image: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=800&q=80',
        promotionalVideoUrl: 'https://www.youtube.com/embed/o0k8xGzhoU8?autoplay=0',
        totalLessons: 19,
        whatYouWillLearn: [
            'Master the Next.js App Router and Server Components.',
            'Implement SSR, SSG, and ISR.',
            'Connect Next.js to various databases (e.g., PostgreSQL, MongoDB).',
        ],
        curriculum: [
            {
                id: 201,
                title: 'Section 1: Next.js Fundamentals & App Router',
                duration: '7 lectures | 6h 0m',
                lessons: ['Introduction to Next.js 15', 'Setting up the Environment', 'Pages vs. Layouts'],
                isPreviewable: true,
            },
            {
                id: 202,
                title: 'Section 2: Server Components and Data Fetching',
                duration: '5 lectures | 4h 30m',
                lessons: ['Server vs Client Components', 'Data Fetching Patterns', 'Caching Strategies'],
                isPreviewable: false,
            },
            {
                id: 203,
                title: 'Section 3: API Routes and Backend Integration',
                duration: '6 lectures | 5h 15m',
                lessons: ['Creating API Routes', 'Database Connections', 'Middleware and Authentication'],
                isPreviewable: true,
            },
            {
                id: 204,
                title: 'Section 4: Advanced Features',
                duration: '4 lectures | 3h 45m',
                lessons: ['Image Optimization', 'Internationalization', 'Static Generation'],
                isPreviewable: false,
            },
            {
                id: 205,
                title: 'Section 5: Deployment and Production',
                duration: '3 lectures | 2h 30m',
                lessons: ['Vercel Deployment', 'Performance Monitoring', 'Best Practices'],
                isPreviewable: true,
            },
        ],
        requirements: ['Solid understanding of React and JavaScript ES6+.'],
    },
    {
        id: 3,
        title: "Beginner's Guide to JavaScript and React (Zero to Hero)",
        categories: ['Programming Basics', 'JavaScript', 'React', 'Web Development'],
        instructor: {
            name: 'Clara Diaz',
            title: 'Coding Instructor & Developer',
            rating: 4.9,
            reviews: 35000,
        },
        description:
            'Start your coding journey! This course covers all the JavaScript fundamentals and introduces you to building simple web applications with React.',
        price: 99.99,
        level: 'Beginner',
        discountPrice: 14.99,
        rating: 4.9,
        totalReviews: 185000,
        studentsEnrolled: 510000,
        lastUpdated: 'September 2025',
        language: 'Spanish',
        durationHours: 20.0,
        isBestseller: true,
        published: true,
        image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80',
        promotionalVideoUrl: 'https://www.youtube.com/embed/rfTsy8M_w3Q?autoplay=0',
        totalLessons: 32,
        whatYouWillLearn: [
            'Master JavaScript variables, functions, loops, and arrays.',
            'Understand the basics of the Document Object Model (DOM).',
            'Build your first basic React components.',
        ],
        curriculum: [
            {
                id: 301,
                title: 'Section 1: JavaScript Fundamentals',
                duration: '15 lectures | 10h 0m',
                lessons: ['JS Introduction', 'Variables and Data Types', 'Operators'],
                isPreviewable: true,
            },
            {
                id: 302,
                title: 'Section 2: Control Flow and Functions',
                duration: '10 lectures | 7h 30m',
                lessons: ['Conditionals', 'Loops', 'Functions', 'Scope and Closures'],
                isPreviewable: false,
            },
            {
                id: 303,
                title: 'Section 3: Objects and Arrays',
                duration: '8 lectures | 6h 0m',
                lessons: ['Working with Objects', 'Array Methods', 'ES6 Features', 'DOM Manipulation'],
                isPreviewable: true,
            },
            {
                id: 304,
                title: 'Section 4: Introduction to React',
                duration: '12 lectures | 9h 0m',
                lessons: ['What is React?', 'JSX Syntax', 'Components', 'Props and State'],
                isPreviewable: false,
            },
            {
                id: 305,
                title: 'Section 5: Building React Applications',
                duration: '7 lectures | 5h 30m',
                lessons: ['Event Handling', 'Forms', 'Lifecycle Methods', 'Simple Projects'],
                isPreviewable: true,
            },
        ],
        requirements: ['No prior programming experience required.'],
    },
    {
        id: 4,
        title: 'React Performance Optimization & Best Practices',
        categories: ['React', 'Performance', 'Advanced', 'Frontend'],
        instructor: {
            name: 'David Chen',
            title: 'Principal Engineer',
            rating: 4.7,
            reviews: 7200,
        },
        description:
            'Dive deep into optimizing React applications for speed. Learn memoization, virtualization, code splitting, and advanced profiling.',
        price: 129.99,
        level: 'Advanced',
        discountPrice: 29.99,
        rating: 4.7,
        totalReviews: 18500,
        studentsEnrolled: 48000,
        lastUpdated: 'August 2025',
        language: 'English',
        durationHours: 18.0,
        isBestseller: false,
        published: true,
        image: 'https://images.unsplash.com/photo-1627398242474-ad71c778465d?w=800&q=80',
        promotionalVideoUrl: 'https://www.youtube.com/embed/M_7t-v-gR54?autoplay=0',
        totalLessons: 15,
        whatYouWillLearn: [
            'Utilize useMemo, useCallback, and React.memo effectively.',
            'Implement lazy loading and code splitting with Suspense.',
            'Identify and fix rendering bottlenecks using the React Profiler.',
        ],
        curriculum: [
            {
                id: 401,
                title: 'Section 1: Memoization Techniques',
                duration: '6 lectures | 4h 30m',
                lessons: ['Understanding Reconciliation', 'useMemo in Depth', 'React.memo for Components'],
                isPreviewable: false,
            },
            {
                id: 402,
                title: 'Section 2: Code Splitting and Lazy Loading',
                duration: '4 lectures | 3h 15m',
                lessons: ['React.lazy and Suspense', 'Dynamic Imports', 'Route-based Splitting'],
                isPreviewable: true,
            },
            {
                id: 403,
                title: 'Section 3: Profiling and Debugging',
                duration: '5 lectures | 4h 0m',
                lessons: ['React DevTools Profiler', 'Performance Monitoring', 'Identifying Bottlenecks'],
                isPreviewable: false,
            },
            {
                id: 404,
                title: 'Section 4: Advanced Optimization Patterns',
                duration: '3 lectures | 2h 45m',
                lessons: ['Virtualization', 'Windowing Techniques', 'Bundle Analysis'],
                isPreviewable: true,
            },
        ],
        requirements: ['Strong foundation in React Hooks.'],
    },
    {
        id: 5,
        title: 'State Management with Zustand and Jotai',
        categories: ['React', 'State Management', 'Frontend', 'JavaScript'],
        instructor: {
            name: 'Elena Smith',
            title: 'Frontend Architect',
            rating: 4.5,
            reviews: 5100,
        },
        description:
            'Move beyond Redux and Context. Master modern, lightweight state management solutions like Zustand and Jotai for large applications.',
        price: 109.99,
        level: 'Intermediate',
        discountPrice: 24.99,
        rating: 4.5,
        totalReviews: 11200,
        studentsEnrolled: 31000,
        lastUpdated: 'July 2025',
        language: 'English',
        durationHours: 15.0,
        isBestseller: false,
        published: true,
        image: 'https://images.unsplash.com/photo-1613945952932-d610815e9c0b?w=800&q=80',
        promotionalVideoUrl: 'https://www.youtube.com/embed/jC71vD4E4e4?autoplay=0',
        totalLessons: 12,
        whatYouWillLearn: [
            'Implement state stores using Zustand (stores, middleware).',
            'Manage atomic state with Jotai (atoms, derived state).',
            'Integrate asynchronous data fetching (e.g., SWR/TanStack Query) with lightweight state.',
        ],
        curriculum: [
            {
                id: 501,
                title: 'Section 1: Introduction to Lightweight State',
                duration: '4 lectures | 3h 0m',
                lessons: ['Why New State Managers?', 'Zustand Setup', 'Jotai Atoms'],
                isPreviewable: true,
            },
            {
                id: 502,
                title: 'Section 2: Zustand in Depth',
                duration: '3 lectures | 2h 30m',
                lessons: ['Stores and Actions', 'Middleware', 'Async Operations'],
                isPreviewable: false,
            },
            {
                id: 503,
                title: 'Section 3: Jotai Advanced Features',
                duration: '3 lectures | 2h 15m',
                lessons: ['Derived Atoms', 'Atom Families', 'Integration Patterns'],
                isPreviewable: true,
            },
        ],
        requirements: ['Familiarity with functional React components.'],
    },
    {
        id: 6,
        title: 'Building E-Commerce with MERN Stack (React, Node, Express, MongoDB)',
        categories: ['Full Stack Development', 'MERN', 'React', 'Databases'],
        instructor: {
            name: 'Frank Green',
            title: 'Full Stack Consultant',
            rating: 4.8,
            reviews: 15000,
        },
        description:
            'A hands-on, project-based course to build and deploy a complete E-Commerce platform using the MERN stack from scratch.',
        price: 249.99,
        level: 'Intermediate',
        discountPrice: 59.99,
        rating: 4.7,
        totalReviews: 35000,
        studentsEnrolled: 120000,
        lastUpdated: 'October 2025',
        language: 'English',
        durationHours: 60.0,
        isBestseller: true,
        published: true,
        image: 'https://images.unsplash.com/photo-1601004944445-5f212970503f?w=800&q=80',
        promotionalVideoUrl: 'https://www.youtube.com/embed/sLqC3J-D1X8?autoplay=0',
        totalLessons: 45,
        whatYouWillLearn: [
            'Set up robust backend APIs with Node/Express.',
            'Design and manage MongoDB schemas.',
            'Integrate React with the backend for data fetching and mutations.',
            'Implement user authentication, product catalogs, and payment gateways.',
        ],
        curriculum: [
            {
                id: 601,
                title: 'Section 1: Backend Setup (Node/Express)',
                duration: '10 lectures | 8h 0m',
                lessons: ['Server Initialization', 'API Structure', 'MongoDB Connection'],
                isPreviewable: false,
            },
            {
                id: 602,
                title: 'Section 2: Database Design and Models',
                duration: '8 lectures | 6h 30m',
                lessons: ['MongoDB Schemas', 'User Authentication', 'Product Models'],
                isPreviewable: true,
            },
            {
                id: 603,
                title: 'Section 3: Frontend Integration',
                duration: '12 lectures | 10h 0m',
                lessons: ['React Setup', 'API Calls', 'State Management', 'Cart Functionality'],
                isPreviewable: false,
            },
            {
                id: 604,
                title: 'Section 4: Payment and Deployment',
                duration: '6 lectures | 5h 30m',
                lessons: ['Stripe Integration', 'Order Processing', 'Production Deployment'],
                isPreviewable: true,
            },
        ],
        requirements: ['Intermediate React knowledge.'],
    },
    {
        id: 7,
        title: 'React Native: iOS and Android App Development',
        categories: ['Mobile Development', 'React Native', 'React', 'Cross-Platform'],
        instructor: {
            name: 'Grace Hall',
            title: 'Mobile Lead Developer',
            rating: 4.6,
            reviews: 11000,
        },
        description:
            'Build truly native mobile apps for both iOS and Android using React Native. Master Expo, navigation, and device APIs.',
        price: 179.99,
        level: 'Intermediate',
        discountPrice: 44.99,
        rating: 4.6,
        totalReviews: 30500,
        studentsEnrolled: 110000,
        lastUpdated: 'November 2025',
        language: 'English',
        durationHours: 40.0,
        isBestseller: true,
        published: true,
        image: 'https://images.unsplash.com/photo-1628102491629-87a177218684?w=800&q=80',
        promotionalVideoUrl: 'https://www.youtube.com/embed/0I6B8s8mQ4o?autoplay=0',
        totalLessons: 35,
        whatYouWillLearn: [
            'Use React Native components and styling for mobile UI.',
            'Implement deep navigation using React Navigation.',
            'Access native features (Camera, Geolocation) using Expo APIs.',
            'Publish apps to Apple App Store and Google Play Store.',
        ],
        curriculum: [
            {
                id: 701,
                title: 'Section 1: RN Setup and Basics',
                duration: '7 lectures | 5h 20m',
                lessons: ['What is React Native?', 'Expo vs CLI', 'Core Components'],
                isPreviewable: true,
            },
            {
                id: 702,
                title: 'Section 2: Navigation and Routing',
                duration: '5 lectures | 4h 0m',
                lessons: ['React Navigation', 'Stack Navigator', 'Tab Navigator'],
                isPreviewable: false,
            },
            {
                id: 703,
                title: 'Section 3: Native Features and APIs',
                duration: '6 lectures | 5h 15m',
                lessons: ['Camera Access', 'Geolocation', 'AsyncStorage'],
                isPreviewable: true,
            },
            {
                id: 704,
                title: 'Section 4: Building and Publishing',
                duration: '4 lectures | 3h 30m',
                lessons: ['Testing Apps', 'Build Process', 'App Store Submission'],
                isPreviewable: false,
            },
        ],
        requirements: ['React and JavaScript knowledge.'],
    },
    {
        id: 8,
        title: 'Modern React Testing with Jest and React Testing Library',
        categories: ['Testing', 'React', 'Frontend', 'Quality Assurance'],
        instructor: {
            name: 'Henry Isaacs',
            title: 'Software Quality Engineer',
            rating: 4.9,
            reviews: 4500,
        },
        description:
            'Learn to write robust and maintainable tests for your React applications using Jest and the user-centric React Testing Library.',
        price: 89.99,
        level: 'Intermediate',
        discountPrice: 19.99,
        rating: 4.8,
        totalReviews: 9100,
        studentsEnrolled: 28000,
        lastUpdated: 'July 2025',
        language: 'English',
        durationHours: 12.5,
        isBestseller: false,
        published: true,
        image: 'https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=800&q=80',
        promotionalVideoUrl: 'https://www.youtube.com/embed/M1QYh1c47oQ?autoplay=0',
        totalLessons: 18,
        whatYouWillLearn: [
            'Set up Jest and React Testing Library (RTL).',
            'Write unit and integration tests for React components.',
            'Mock API calls and external dependencies.',
            'Achieve high test coverage and confidence.',
        ],
        curriculum: [
            {
                id: 801,
                title: 'Section 1: Jest Fundamentals',
                duration: '5 lectures | 3h 0m',
                lessons: ['Test Runners Introduction', 'Basic Jest Matchers', 'Setting up RTL'],
                isPreviewable: true,
            },
            {
                id: 802,
                title: 'Section 2: Testing React Components',
                duration: '6 lectures | 4h 30m',
                lessons: ['Rendering Components', 'User Interactions', 'Mocking Dependencies'],
                isPreviewable: false,
            },
            {
                id: 803,
                title: 'Section 3: Advanced Testing Patterns',
                duration: '4 lectures | 3h 15m',
                lessons: ['Custom Hooks Testing', 'Async Testing', 'Integration Tests'],
                isPreviewable: true,
            },
            {
                id: 804,
                title: 'Section 4: Test Coverage and CI/CD',
                duration: '3 lectures | 2h 15m',
                lessons: ['Coverage Reports', 'GitHub Actions', 'Best Practices'],
                isPreviewable: false,
            },
        ],
        requirements: ['Basic React Hooks experience.'],
    },
    {
        id: 9,
        title: 'Advanced TypeScript for React Developers',
        categories: ['TypeScript', 'React', 'JavaScript', 'Advanced'],
        instructor: {
            name: 'Irene Keller',
            title: 'TypeScript Core Contributor',
            rating: 4.8,
            reviews: 6800,
        },
        description:
            'Leverage the full power of TypeScript in your large-scale React projects. Master generics, utility types, and type-safe Redux/Context.',
        price: 139.99,
        level: 'Advanced',
        discountPrice: 34.99,
        rating: 4.7,
        totalReviews: 15300,
        studentsEnrolled: 40000,
        lastUpdated: 'September 2025',
        language: 'English',
        durationHours: 22.0,
        isBestseller: false,
        published: true,
        image: 'https://images.unsplash.com/photo-1628157529270-ed14798de4b3?w=800&q=80',
        promotionalVideoUrl: 'https://www.youtube.com/embed/nC0T45HwB4w?autoplay=0',
        totalLessons: 20,
        whatYouWillLearn: [
            'Configure TypeScript in a React/Vite project.',
            'Define complex component props and state types.',
            'Use Generics for reusable, type-safe components.',
            'Type Redux/Zustand state management completely.',
        ],
        curriculum: [
            {
                id: 901,
                title: 'Section 1: TS/React Setup',
                duration: '5 lectures | 4h 0m',
                lessons: ['Project Setup with TypeScript', 'Typing Props and State', 'Typing Event Handlers'],
                isPreviewable: true,
            },
            {
                id: 902,
                title: 'Section 2: Advanced Types',
                duration: '6 lectures | 5h 30m',
                lessons: ['Generics', 'Utility Types', 'Conditional Types'],
                isPreviewable: false,
            },
            {
                id: 903,
                title: 'Section 3: TypeScript with Redux/Context',
                duration: '4 lectures | 3h 45m',
                lessons: ['Typed Redux Store', 'Context with TS', 'Custom Hooks'],
                isPreviewable: true,
            },
            {
                id: 904,
                title: 'Section 4: Real-World TypeScript Projects',
                duration: '5 lectures | 4h 15m',
                lessons: ['Large App Architecture', 'Type Safety Best Practices', 'Migration Strategies'],
                isPreviewable: false,
            },
        ],
        requirements: ['Working knowledge of React and basic TypeScript syntax.'],
    },
    {
        id: 10,
        title: 'React with Firebase: Build a Real-Time Chat App',
        categories: ['Full Stack Development', 'React', 'Firebase', 'Realtime'],
        instructor: {
            name: 'Jacob Lee',
            title: 'Cloud Developer Advocate',
            rating: 4.5,
            reviews: 8500,
        },
        description:
            'Learn to use Google Firebase (Firestore, Authentication, Storage) as a backend for your React applications. Build a fully functional chat application.',
        price: 119.99,
        level: 'Intermediate',
        discountPrice: 29.99,
        rating: 4.5,
        totalReviews: 20100,
        studentsEnrolled: 65000,
        lastUpdated: 'June 2025',
        language: 'English',
        durationHours: 19.5,
        isBestseller: false,
        published: true,
        image: 'https://images.unsplash.com/photo-1587440051664-9f70d5a86a6a?w=800&q=80',
        promotionalVideoUrl: 'https://www.youtube.com/embed/7E64b4cI3xQ?autoplay=0',
        totalLessons: 25,
        whatYouWillLearn: [
            'Set up Firebase Authentication (Email/Password, Google Sign-In).',
            'Perform CRUD operations with Firestore.',
            'Implement real-time data synchronization.',
            'Manage file uploads with Firebase Storage.',
        ],
        curriculum: [
            {
                id: 1001,
                title: 'Section 1: Firebase Setup and Auth',
                duration: '6 lectures | 4h 15m',
                lessons: ['Firebase Project Creation', 'Integrating with React', 'Email/Password Auth'],
                isPreviewable: true,
            },
            {
                id: 1002,
                title: 'Section 2: Firestore Database',
                duration: '5 lectures | 4h 0m',
                lessons: ['CRUD Operations', 'Real-time Listeners', 'Security Rules'],
                isPreviewable: false,
            },
            {
                id: 1003,
                title: 'Section 3: Building the Chat App',
                duration: '8 lectures | 7h 30m',
                lessons: ['UI Components', 'Message Sending', 'Real-time Updates', 'File Uploads'],
                isPreviewable: true,
            },
            {
                id: 1004,
                title: 'Section 4: Deployment and Optimization',
                duration: '4 lectures | 3h 15m',
                lessons: ['Firebase Hosting', 'Performance Tips', 'Security Best Practices'],
                isPreviewable: false,
            },
        ],
        requirements: ['Basic to Intermediate React knowledge.'],
    },
    {
        id: 11,
        title: 'React and GraphQL: Apollo Client Mastery',
        categories: ['GraphQL', 'React', 'API Development', 'Frontend'],
        instructor: {
            name: 'Katherine White',
            title: 'Lead GraphQL Developer',
            rating: 4.7,
            reviews: 9500,
        },
        description:
            'Master fetching and managing complex data in React using GraphQL and the Apollo Client. Includes mutations, caching, and subscriptions.',
        price: 159.99,
        level: 'Intermediate',
        discountPrice: 39.99,
        rating: 4.6,
        totalReviews: 25400,
        studentsEnrolled: 78000,
        lastUpdated: 'October 2025',
        language: 'English',
        durationHours: 25.0,
        isBestseller: true,
        published: true,
        image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80',
        promotionalVideoUrl: 'https://www.youtube.com/embed/Z0oYxGv_6sM?autoplay=0',
        totalLessons: 30,
        whatYouWillLearn: [
            'Understand the benefits of GraphQL over REST.',
            'Set up and configure Apollo Client in a React app.',
            'Write queries and mutations for data manipulation.',
            'Implement complex caching policies and real-time updates.',
        ],
        curriculum: [
            {
                id: 1101,
                title: 'Section 1: GraphQL Fundamentals',
                duration: '8 lectures | 6h 0m',
                lessons: ['Introduction to GraphQL', 'Writing your first Query', 'Setting up Apollo'],
                isPreviewable: false,
            },
            {
                id: 1102,
                title: 'Section 2: Queries and Mutations',
                duration: '6 lectures | 5h 15m',
                lessons: ['Advanced Queries', 'Mutations', 'Error Handling'],
                isPreviewable: true,
            },
            {
                id: 1103,
                title: 'Section 3: Caching and State Management',
                duration: '5 lectures | 4h 30m',
                lessons: ['Apollo Cache', 'Local State', 'Optimistic Updates'],
                isPreviewable: false,
            },
            {
                id: 1104,
                title: 'Section 4: Advanced Features',
                duration: '4 lectures | 3h 45m',
                lessons: ['Subscriptions', 'Fragments', 'Code Generation'],
                isPreviewable: true,
            },
        ],
        requirements: ['Intermediate React knowledge.'],
    },
    {
        id: 12,
        title: 'React Design Systems with Storybook and Tailwind CSS',
        categories: ['UI/UX', 'React', 'Design', 'CSS'],
        instructor: {
            name: 'Liam Murphy',
            title: 'Frontend & UI/UX Expert',
            rating: 4.8,
            reviews: 5500,
        },
        description:
            'Learn to build reusable, accessible, and beautiful component libraries using React, Storybook for documentation, and Tailwind CSS for utility-first styling.',
        price: 99.99,
        level: 'Intermediate',
        discountPrice: 22.99,
        rating: 4.7,
        totalReviews: 13800,
        studentsEnrolled: 35000,
        lastUpdated: 'August 2025',
        language: 'English',
        durationHours: 16.0,
        isBestseller: false,
        published: true,
        image: 'https://images.unsplash.com/photo-1518770660439-463d12558661?w=800&q=80',
        promotionalVideoUrl: 'https://www.youtube.com/embed/5F_oQ_kE1q8?autoplay=0',
        totalLessons: 20,
        whatYouWillLearn: [
            'Build a Design System foundation (tokens, typography).',
            'Master Tailwind CSS for rapid, scalable styling.',
            'Document and test components using Storybook.',
            'Ensure component accessibility (A11y).',
        ],
        curriculum: [
            {
                id: 1201,
                title: 'Section 1: Styling with Tailwind',
                duration: '5 lectures | 3h 15m',
                lessons: ['Tailwind Setup', 'Utility-First Approach', 'Responsive Design'],
                isPreviewable: true,
            },
            {
                id: 1202,
                title: 'Section 2: Building Components',
                duration: '6 lectures | 4h 45m',
                lessons: ['Component Library', 'Design Tokens', 'Accessibility'],
                isPreviewable: false,
            },
            {
                id: 1203,
                title: 'Section 3: Storybook Integration',
                duration: '4 lectures | 3h 30m',
                lessons: ['Storybook Setup', 'Writing Stories', 'Testing Components'],
                isPreviewable: true,
            },
            {
                id: 1204,
                title: 'Section 4: Design System Best Practices',
                duration: '5 lectures | 4h 0m',
                lessons: ['Documentation', 'Versioning', 'Team Collaboration'],
                isPreviewable: false,
            },
        ],
        requirements: ['Familiarity with CSS and React.'],
    },
    {
        id: 13,
        title: 'Remix Framework: Full Stack React with Web Standards',
        categories: ['Full Stack Development', 'React', 'Remix', 'Web Standards'],
        instructor: {
            name: 'Maria Rodriguez',
            title: 'Senior Frontend Developer',
            rating: 4.7,
            reviews: 6100,
        },
        description:
            'Learn to build fast, resilient applications using the Remix framework. Focus on web fundamentals, nested routing, and server-side data mutations.',
        price: 149.99,
        level: 'Intermediate',
        discountPrice: 39.99,
        rating: 4.6,
        totalReviews: 14500,
        studentsEnrolled: 42000,
        lastUpdated: 'October 2025',
        language: 'English',
        durationHours: 28.0,
        isBestseller: false,
        published: true,
        image: 'https://images.unsplash.com/photo-1593720216773-673b224e75d5?w=800&q=80',
        promotionalVideoUrl: 'https://www.youtube.com/embed/e_31Q25o1Q4?autoplay=0',
        totalLessons: 24,
        whatYouWillLearn: [
            'Master nested routing and layout structures in Remix.',
            'Utilize Loaders for data fetching on the server.',
            'Handle data mutations with Actions and Forms.',
            'Deploy Remix applications to various environments.',
        ],
        curriculum: [
            {
                id: 1301,
                title: 'Section 1: Remix Core Concepts',
                duration: '7 lectures | 5h 30m',
                lessons: ['Project Structure', 'Loaders and Actions', 'Handling Forms'],
                isPreviewable: true,
            },
            {
                id: 1302,
                title: 'Section 2: Routing and Nested Routes',
                duration: '5 lectures | 4h 15m',
                lessons: ['Nested Routing', 'Dynamic Routes', 'Layout Routes'],
                isPreviewable: false,
            },
            {
                id: 1303,
                title: 'Section 3: Data Fetching and Mutations',
                duration: '6 lectures | 5h 0m',
                lessons: ['Server-Side Data', 'Optimistic UI', 'Error Boundaries'],
                isPreviewable: true,
            },
            {
                id: 1304,
                title: 'Section 4: Deployment and Production',
                duration: '4 lectures | 3h 45m',
                lessons: ['Build Process', 'Hosting', 'Performance Optimization'],
                isPreviewable: false,
            },
        ],
        requirements: ['Strong React and routing fundamentals.'],
    },
];

export default data;
